language: r
r: bioc-devel
sudo: required
cache: packages
notifications:
  slack:
    secure: kOlKCsRSvYuEeH6pmiajdeNTS5yf2g91a2V2kxGHwKAK61I3B7Et00bzelP41cXMBW0t1Ash8iPzw1cbqxKm6tF9MPxP5lqduAWQfW86d8Imiy2kDlo01GKSBuAfFJfLHVwS7wjR0Cl083nmUdruJnzFKruT469Sl48YUYTgVnChtnJUmzTsYUm5tlbju1p92HX3yk4ToOSand9g3dyWrDpjCwp+i16QSyNeUk2drMPPQuuWNqBVSXzf/FmyVGUeuKONIfeQl5fTJncQIq2YSG0naTkd16F4ro1frz5rIgtNnjNgiWbhkLFChI0XePVlsNPiYZXeFsIimS+y5RG3sjLfL7W2p5L/ZJXJju5L4dfGdvCNg7dqAkfD6Af99a0rj7aJU3XUPn0lvTaFmL/ixnqEJIa/3qcDgST2wr5xlxeJaOksGzPy+0uZYhWlkKJeNOt4n5u1nOP4bsFvBzIaFRx8deDn2auuEMhx3BVlpWfkj6+LidTdgBwNEXXlChhwpf8VR7To09RnuvVTvViZjTljbKn0D/eFC8pZTIQ5dTi6DZQVRlqRG4dddeQdZpI+i1lQIFO+nQdOFAZznLetroPo+Tl+oN4oACesieg3D6GJc0oZhQKmPpWIx0Y5J07Q46pd4w6/8zODts/89GLWd+hm/EZHDciCfzE8pbKQ/ZE=