language: r
r: bioc-devel
sudo: required
cache: packages

r_github_packages:
  - jimhester/covr

notifications:
  slack:
    rooms:
      secure: bkZRdDrN940D/pE66l6rf3t0015/VbB8MxOrphBjrxXxLw1KomT0jHYqNDn1Ly8XimdGIRnR8KiMeI/e1AHld5h1DF0ccnsuA4NvAfgyFDxOjMC1KBJ6FswdxKNPgInYxrfKrsC2m8pUmOoVI5SHq6tz99CbpeMl7iOAgMD5rMs5uXLCTILObKKqg7ZNF5RHHuf6D4lZQwmH0g7T0fYU74gN583mkQyNuJCK0HOkNBjCl+TCGZNHDzrH4JrW6sdnEhYbfZrJi3lYSCJsOyGmkMDE6TAocrXhJvDU3p2boCTDn8NObGeNEr4T8GmnFLMyYtNvHuBAnITWcSXjJmMScuzHajNXJ2/CGjRhgQxL5jL2UIg6jvFKwKUse4e+gTmwiapo2sele+g6oJDQyz9eiQCHZkPaTCoPuqkpDeo7WQo41V5VGPyPGCGqglUFk0STBDk7n2TGCatzfuxOO7qGp+00VLp0sm3iI4W8fjJLBb9pkijeq87NTWRobqvo7A5emh3n1yY8/eScvog6bd2ZKmpTqhKRMzEIGCiwktGwHhsvGunr4lARiPH6/9uFochdlLsfCKwaCx/fILw2zdoignsx50B5a06ycDh2pvuoRut1hN1+3lfyTaqHMeU2UNRY0mIS0m+27QsTZH7vSI0FjUVFWaGUB1ChHKODjlax9HM=
